### ISSUE TITLE
clicking "open" crashes

### ISSUE THREAD

**Issue by Eddio0141** [icsharpcode/AvaloniaILSpy#133]
ran on an arch linux system, program opens but clicking the button crashes the program with the exception:
```
System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'. (Parameter 'bytes')
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar)
   at System.Text.UTF8Encoding.GetBytes(String s, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex)
   at Avalonia.FreeDesktop.NativeMethods.ReadLink(String path) in /_/src/Avalonia.FreeDesktop/NativeMethods.cs:line 25
   at Avalonia.FreeDesktop.LinuxMountedVolumeInfoListener.GetSymlinkTarget(String x) in /_/src/Avalonia.FreeDesktop/LinuxMountedVolumeInfoListener.cs:line 37
   at Avalonia.FreeDesktop.LinuxMountedVolumeInfoListener.<Poll>b__8_7(FileInfo x) in /_/src/Avalonia.FreeDesktop/LinuxMountedVolumeInfoListener.cs:line 57
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Lookup`2.CreateForJoin(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.GroupJoinIterator[TOuter,TInner,TKey,TResult](IEnumerable`1 outer, IEnumerable`1 inner, Func`2 outerKeySelector, Func`2 innerKeySelector, Func`3 resultSelector, IEqualityComparer`1 comparer)+MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Avalonia.FreeDesktop.LinuxMountedVolumeInfoListener.Poll(Int64 _) in /_/src/Avalonia.FreeDesktop/LinuxMountedVolumeInfoListener.cs:line 41
   at Avalonia.FreeDesktop.LinuxMountedVolumeInfoListener..ctor(ObservableCollection`1& target) in /_/src/Avalonia.FreeDesktop/LinuxMountedVolumeInfoListener.cs:line 34
   at Avalonia.FreeDesktop.LinuxMountedVolumeInfoProvider.Listen(ObservableCollection`1 mountedDrives) in /_/src/Avalonia.FreeDesktop/LinuxMountedVolumeInfoProvider.cs:line 13
   at Avalonia.Dialogs.ManagedFileChooserViewModel..ctor(FileSystemDialog dialog, ManagedFileDialogOptions options) in /_/src/Avalonia.Dialogs/ManagedFileChooserViewModel.cs:line 116
   at Avalonia.Dialogs.ManagedFileDialogExtensions.ManagedSystemDialogImpl`1.Show(SystemDialog d, Window parent, ManagedFileDialogOptions options) in /_/src/Avalonia.Dialogs/ManagedFileDialogExtensions.cs:line 14
   at Avalonia.Dialogs.ManagedFileDialogExtensions.ManagedSystemDialogImpl`1.ShowFileDialogAsync(FileDialog dialog, Window parent) in /_/src/Avalonia.Dialogs/ManagedFileDialogExtensions.cs:line 42
   at ICSharpCode.ILSpy.MainWindow.OpenCommandExecuted(Object sender, ExecutedRoutedEventArgs e) in /home/yuu0141/.cache/paru/clone/avaloniailspy/src/AvaloniaILSpy/ILSpy.Core/MainWindow.xaml.cs:line 1106
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object stat
e)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at ICSharpCode.ILSpy.Program.Main(String[] args) in /home/yuu0141/.cache/paru/clone/avaloniailspy/src/AvaloniaILSpy/ILSpy/Program.cs:line 22
```

**Comment by Inevitabilis** [comment]
kde neon, same as first comment
