### ISSUE TITLE
Loading assemblies on Mac doesn't work

### ISSUE THREAD

**Issue by filipnavara** [icsharpcode/AvaloniaILSpy#2]
```
// /Volumes/BOOTCAMP/Windows/Microsoft.NET/Framework/v2.0.50727/System.Security.dll
// PE file does not contain any managed metadata.

ICSharpCode.Decompiler.Metadata.PEFileNotSupportedException: PE file does not contain any managed metadata.
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, PEReader reader)
   at ICSharpCode.Decompiler.Metadata.PEFile..ctor(String fileName, Stream stream, PEStreamOptions options)
   at ICSharpCode.ILSpy.LoadedAssembly.LoadAssembly(Object state)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
```

**Comment by jeffreye** [comment]
Looks like your file does not contain any managed code. When I decompiled my System.Security.dll, it does work. 
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1737680/45588730-4ed29f00-b8ce-11e8-8ceb-ec6dbdda624c.png">
