### ISSUE TITLE
Crashes in Ubuntu 18.04 when trying to change the font

### ISSUE THREAD

**Issue by damageboy** [icsharpcode/AvaloniaILSpy#7]
```

(ILSpy:31509): GLib-GObject-CRITICAL **: 16:27:33.927: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed

(ILSpy:31509): GLib-GObject-WARNING **: 16:27:33.927: instance with invalid (NULL) class pointer

(ILSpy:31509): GLib-GObject-CRITICAL **: 16:27:33.927: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(ILSpy:31509): GLib-GObject-WARNING **: 16:27:33.927: instance with invalid (NULL) class pointer

(ILSpy:31509): GLib-GObject-CRITICAL **: 16:27:33.927: g_signal_handlers_destroy: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at ICSharpCode.ILSpy.Options.FontSizeConverter.ConvertBack(Object value, Type targetType, Object parameter, CultureInfo culture)
   at Avalonia.Data.Core.BindingExpression.OnNext(Object value)
   at Avalonia.Reactive.LightweightObservableBase`1.Subscribe(IObserver`1 observer)
   at Avalonia.Data.BindingOperations.Apply(IAvaloniaObject target, AvaloniaProperty property, InstancedBinding binding, Object anchor)
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
   at Avalonia.Markup.Data.DelayedBinding.BindingEntry.Apply(IStyledElement control)
   at Avalonia.Markup.Data.DelayedBinding.ApplyBindings(IStyledElement control)
   at Avalonia.Markup.Data.DelayedBinding.ApplyBindings(Object sender, EventArgs e)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Controls.Control.OnAttachedToVisualTreeCore(VisualTreeAttachmentEventArgs e)
   at Avalonia.Visual.SetVisualParent(Visual value)
   at Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)
   at Avalonia.Controls.Presenters.ContentPresenter.UpdateChild()
   at Avalonia.Controls.Presenters.ContentPresenter.ContentChanged(AvaloniaPropertyChangedEventArgs e)
   at System.Reactive.Observer`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Observers.cs:line 80
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority)
   at Avalonia.AvaloniaObject.PriorityValueChanged(AvaloniaProperty property, Int32 priority, Object oldValue, Object newValue)
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification)
   at Avalonia.PriorityValue.UpdateCore(ValueTuple`2 update, ValueTuple`2& backing, Action`1 notify)
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value)
   at Avalonia.PriorityValue.UpdateValue(Object value, Int32 priority)
   at Avalonia.Data.TemplateBinding.Subscribed()
   at Avalonia.Reactive.SingleSubscriberObservableBase`1.Subscribe(IObserver`1 observer)
   at Avalonia.PriorityBindingEntry.Start(IObservable`1 binding)
   at Avalonia.PriorityLevel.Add(IObservable`1 binding)
   at Avalonia.ValueStore.AddBinding(AvaloniaProperty property, IObservable`1 source, BindingPriority priority)
   at Avalonia.AvaloniaObjectExtensions.Bind(IAvaloniaObject target, AvaloniaProperty property, IBinding binding, Object anchor)
   at Avalonia.Markup.Data.DelayedBinding.BindingEntry.Apply(IStyledElement control)
   at Avalonia.Markup.Data.DelayedBinding.ApplyBindings(IStyledElement control)
   at Avalonia.Markup.Data.DelayedBinding.ApplyBindings(Object sender, EventArgs e)
   at Avalonia.Visual.SetVisualParent(Visual value)
   at Avalonia.Visual.VisualChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize)
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize)
   at Avalonia.Layout.Layoutable.Measure(Size availableSize)
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
   at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
   at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Gtk3.Gtk3Platform.<>c__DisplayClass29_0.<Signal>b__0()
   at Avalonia.Gtk3.Interop.GlibTimeout.Handler(IntPtr data)
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Application.Run(Window mainWindow)
   at ICSharpCode.ILSpy.Program.Main(String[] args)
```

**Comment by jeffreye** [comment]
Font options haven't been implemented yet. I will try to get it done before next release.

**Comment by jeffreye** [comment]
It's fixed on latest version. Currently, There are no API for getting all available fonts, but I will include few fonts for selection. Font option implementation status will be tracking on #1 .
