### ISSUE TITLE
Does not work on MacOS

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/AvaloniaILSpy#8]
Jochens-MBP:Downloads jkuehner$ /Users/jkuehner/Downloads/ILSpy.app/Contents/MacOS/ILSpy 
Sorry, we crashed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/jkuehner/Downloads/Themes'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at ICSharpCode.ILSpy.MainWindow.InitializeComponent()
   at ICSharpCode.ILSpy.MainWindow..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance[T]()
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider)
   at ICSharpCode.ILSpy.Program.Main(String[] args)

**Comment by jeffreye** [comment]
Thanks for reporting.
Please check out the latest CI build.
